trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration) src/Youtube2Mp3.sln
  displayName: 'dotnet build $(buildConfiguration)'
